#include <Nova3D/GUI/GUI.hpp>
#include <Nova3D/Core/Logger.hpp>
#include <Nova3D/IO/FileSystem.hpp>
#include <fstream>
#include <regex>

namespace nova3d::gui {
static std::unordered_map<std::string, NGUIElementFactory::Creator> g_creators;
static std::string stateKey(GUIStyleState s){ switch(s){case GUIStyleState::Normal:return "normal";case GUIStyleState::Hover:return "hover";case GUIStyleState::Pressed:return "pressed";case GUIStyleState::Disabled:return "disabled";case GUIStyleState::Focused:return "focused";} return "normal"; }
NGUITheme NGUITheme::dark(){ NGUITheme t; t.name="dark"; t.colors={{"widget.normal",{0.2F,0.2F,0.24F,1}},{"widget.hover",{0.3F,0.3F,0.35F,1}},{"widget.pressed",{0.4F,0.4F,0.5F,1}},{"widget.disabled",{0.14F,0.14F,0.16F,1}},{"widget.focused",{0.2F,0.35F,0.55F,1}},{"text",{1,1,1,1}},{"accent",{0.25F,0.55F,0.95F,1}}}; t.metrics["widget"]={6,4,6,1,4,14}; t.metrics["button"]={8,4,6,1,4,14}; t.metrics["meshviewer"]={6,4,4,1,2,12}; return t; }
NGUITheme NGUITheme::light(){ auto t=dark(); t.name="light"; t.colors["widget.normal"]={0.88F,0.88F,0.9F,1}; t.colors["widget.hover"]={0.78F,0.78F,0.82F,1}; t.colors["widget.pressed"]={0.68F,0.68F,0.72F,1}; t.colors["widget.disabled"]={0.78F,0.78F,0.78F,1}; t.colors["widget.focused"]={0.25F,0.5F,0.9F,1}; t.colors["text"]={0.08F,0.08F,0.08F,1}; return t; }
NGUITheme NGUITheme::custom(const math::Vector4& accent){ auto t=dark(); t.name="custom"; t.colors["accent"]=accent; t.colors["widget.focused"]=accent; return t; }
math::Vector4 NGUIStyleResolver::color(const NGUITheme& theme,const NGUIStyleSheet& sheet,const std::string& widgetType,const std::string& styleClass,GUIStyleState state,const math::Vector4& fallback) const { const std::string keyA=widgetType+"."+stateKey(state); const std::string keyB="widget."+stateKey(state); if(auto c=sheet.classColors.find(styleClass); c!=sheet.classColors.end()){ if(auto v=c->second.find(keyA); v!=c->second.end()) return v->second; if(auto v=c->second.find(keyB); v!=c->second.end()) return v->second; } if(auto t=theme.colors.find(keyA); t!=theme.colors.end()) return t->second; if(auto t=theme.colors.find(keyB); t!=theme.colors.end()) return t->second; return fallback; }
GUIStyleMetrics NGUIStyleResolver::metrics(const NGUITheme& theme,const std::string& widgetType,const GUIStyleMetrics& fallback) const { if(auto it=theme.metrics.find(widgetType); it!=theme.metrics.end()) return it->second; if(auto it=theme.metrics.find("widget"); it!=theme.metrics.end()) return it->second; return fallback; }
void NGUISkin::setTheme(NGUITheme theme){ m_theme=std::move(theme); invalidate(); }
void NGUISkin::invalidate(){ for(auto& cb:m_listeners) cb(); }
void GUIThemeManager::setLightTheme(){ if(m_skin){m_skin->setTheme(NGUITheme::light()); m_isDark=false;}} void GUIThemeManager::setDarkTheme(){ if(m_skin){m_skin->setTheme(NGUITheme::dark()); m_isDark=true;}} void GUIThemeManager::setCustomAccent(const math::Vector4& accent){ if(m_skin) m_skin->setTheme(NGUITheme::custom(accent)); } void GUIThemeManager::toggleLightDark(){ m_isDark?setLightTheme():setDarkTheme(); }
void GUIElement::draw(GUIRenderer& r){ for(auto& c:m_children) if(c->visible) c->draw(r);} bool GUIElement::handle(const GUIInputEvent& ev){ for(auto it=m_children.rbegin();it!=m_children.rend();++it) if((*it)->visible && (*it)->handle(ev)) return true; return false; }
bool GUIWidget::handle(const GUIInputEvent& ev){ if(!enabled||!visible) return false; if(ev.type==GUIInputEvent::Type::MouseMove) hovered=rect.contains((float)ev.x,(float)ev.y); if(ev.type==GUIInputEvent::Type::MouseDown && hovered){pressed=true; focused=true; return true;} if(ev.type==GUIInputEvent::Type::MouseUp){ bool was=pressed; pressed=false; if(was&&hovered&&onClick) onClick(); return was&&hovered;} return GUIElement::handle(ev); }
void GUIWidget::draw(GUIRenderer& r){ NGUIStyleResolver resolver; auto state=!enabled?GUIStyleState::Disabled:(pressed?GUIStyleState::Pressed:(hovered?GUIStyleState::Hover:(focused?GUIStyleState::Focused:GUIStyleState::Normal))); math::Vector4 color = {0.2F,0.2F,0.2F,1.0F}; if(m_skin) color=resolver.color(m_skin->theme(),m_skin->styleSheet(),widgetType(),styleClass,state,color); r.drawQuad(rect,color,0); if(!text.empty()){ auto c=m_skin?m_skin->theme().colors.at("text"):math::Vector4{1,1,1,1}; r.drawText(rect,text,c,1);} GUIElement::draw(r); }
void NMeshViewerWidget::resetView(){ state.orbitYaw=0; state.orbitPitch=0; state.panX=0; state.panY=0; state.zoom=1.0F; }
bool NMeshViewerWidget::handle(const GUIInputEvent& ev){ const bool inside=rect.contains((float)ev.x,(float)ev.y); if(ev.type==GUIInputEvent::Type::MouseWheel && inside){ state.zoom += ev.wheelY*0.05F; if(state.zoom<0.2F) state.zoom=0.2F; return true; } if(ev.type==GUIInputEvent::Type::MouseMove && pressed && focused){ state.orbitYaw += ev.x*0.0005F; state.orbitPitch += ev.y*0.0005F; return true; } if(ev.type==GUIInputEvent::Type::KeyDown && focused){ if(ev.key=='R') resetView(); if(ev.key=='W') state.wireframe=!state.wireframe; return true; } return GUIWidget::handle(ev); }
void NMeshViewerWidget::draw(GUIRenderer& r){ GUIWidget::draw(r); r.drawText({rect.x+8,rect.y+8,rect.w-16,18},"Mesh: "+state.meshPath,state.tint,2); r.drawText({rect.x+8,rect.y+28,rect.w-16,18},"Meshes:"+std::to_string(state.meshCount)+" Materials:"+std::to_string(state.materialCount)+(state.wireframe?" [Wire]":""),state.tint,2); }
std::shared_ptr<GUIElement> GUIContext::findById(const std::string& needle) const { std::function<std::shared_ptr<GUIElement>(const std::shared_ptr<GUIElement>&)> findRec=[&](const std::shared_ptr<GUIElement>& e)->std::shared_ptr<GUIElement>{ if(e->id==needle) return e; for(const auto& c:e->children()){ auto r=findRec(c); if(r) return r; } return nullptr;}; for(const auto& r:m_root){ auto hit=findRec(r); if(hit) return hit;} return nullptr; }
bool GUIContext::route(const GUIInputEvent& ev){ for(auto it=m_root.rbegin();it!=m_root.rend();++it) if((*it)->handle(ev)) return true; return false;} void GUIContext::draw(GUIRenderer& r){ for(auto& e:m_root) if(e->visible) e->draw(r);} void GUIManager::tick(){ if(!m_renderer) return; m_renderer->beginFrame(); m_ctx.draw(*m_renderer); m_renderer->endFrame(); }
NDialogResult NFileDialog::open(const std::string& title,const std::string& filter,bool multi){ core::Logger::info("[GUI] FileDialog open: "+title+" filter="+filter); return {true,multi?std::vector<std::string>{"assets/models/cube.obj","assets/models/sphere.obj"}:std::vector<std::string>{"assets/models/cube.obj"}}; }
NDialogResult NFileDialog::save(const std::string& title,const std::string& filter){ core::Logger::info("[GUI] FileDialog save: "+title+" filter="+filter); return {true,{"sandbox_saved.layout.json"}}; }
NDialogResult NFileDialog::selectFolder(const std::string& title){ core::Logger::info("[GUI] FolderDialog: "+title); return {true,{"assets/models"}}; }
NDialogResult NColorDialog::pick(const math::Vector4& seed){ core::Logger::info("[GUI] ColorDialog fallback backend"); return {true,{},seed}; }
NDialogResult NMessageBox::show(const std::string& title,const std::string& message,Type,Buttons buttons){ core::Logger::info("[GUI] MessageBox: "+title+" / "+message); return {true,{}, {1,1,1,1}, buttons==Buttons::YesNo?1:0}; }
void NGUIElementFactory::registerType(const std::string& type, Creator creator){ g_creators[type]=std::move(creator);} std::shared_ptr<GUIElement> NGUIElementFactory::create(const std::string& type) const { if(auto it=g_creators.find(type); it!=g_creators.end()) return it->second(); return nullptr;} bool NGUIElementFactory::hasType(const std::string& type) const { return g_creators.contains(type);} 
bool NGUILayoutLoader::loadLayoutJson(const std::string& path, GUIContext& ctx, const NGUIElementFactory& factory, std::shared_ptr<NGUISkin> skin){ io::FileSystem fs; auto content=fs.readText(path); if(content.empty()){ core::Logger::error("[GUI] Layout not found: "+path); return false; } std::regex re("\\{\\s*\\\"type\\\":\\\"([^\\\"]+)\\\",\\s*\\\"id\\\":\\\"([^\\\"]+)\\\",\\s*\\\"parent\\\":\\\"([^\\\"]*)\\\",\\s*\\\"text\\\":\\\"([^\\\"]*)\\\".*?\\\"x\\\":([0-9\\.-]+),\\\"y\\\":([0-9\\.-]+),\\\"w\\\":([0-9\\.-]+),\\\"h\\\":([0-9\\.-]+).*?\\\"visible\\\":(true|false),\\\"enabled\\\":(true|false),\\\"styleClass\\\":\\\"([^\\\"]*)\\\",\\\"onClick\\\":\\\"([^\\\"]*)\\\""); std::smatch m; std::string s=content; std::vector<std::shared_ptr<GUIElement>> made; while(std::regex_search(s,m,re)){ auto e=factory.create(m[1]); if(!e){ s=m.suffix(); continue;} e->id=m[2]; e->parentId=m[3]; if(auto w=std::dynamic_pointer_cast<GUIWidget>(e)){ w->text=m[4]; w->setSkin(skin);} e->rect={std::stof(m[5]),std::stof(m[6]),std::stof(m[7]),std::stof(m[8])}; e->visible=m[9]=="true"; e->enabled=m[10]=="true"; e->styleClass=m[11]; e->onClickAction=m[12]; made.push_back(e); s=m.suffix(); }
 if(made.empty()) return false; for(auto& e:made){ if(e->parentId.empty()) ctx.addRoot(e); else { auto p=ctx.findById(e->parentId); if(p) p->addChild(e); else ctx.addRoot(e);} } return true; }
bool NGUILayoutSerializer::saveLayoutJson(const std::string& path, const GUIContext& ctx){ std::ofstream out(path); if(!out.is_open()) return false; out << "{\n  \"version\":1,\n  \"widgets\":[\n"; bool first=true; for(const auto& r:ctx.roots()){ if(!first) out << ",\n"; first=false; auto* w=dynamic_cast<GUIWidget*>(r.get()); out << "    {\"type\":\""<<(w?w->widgetType():"widget")<<"\",\"id\":\""<<r->id<<"\",\"parent\":\""<<r->parentId<<"\",\"text\":\""<<(w?w->text:"")<<"\",\"rect\":{\"x\":"<<r->rect.x<<",\"y\":"<<r->rect.y<<",\"w\":"<<r->rect.w<<",\"h\":"<<r->rect.h<<"},\"visible\":"<<(r->visible?"true":"false")<<",\"enabled\":"<<(r->enabled?"true":"false")<<",\"styleClass\":\""<<r->styleClass<<"\",\"onClick\":\""<<r->onClickAction<<"\"}"; }
 out << "\n  ]\n}\n"; return true; }
} // namespace
