#pragma once

#include <cstdint>

namespace N {

enum class NKEY_CODE : std::uint16_t {
    NKEY_UNKNOWN = 0,

    NKEY_A, NKEY_B, NKEY_C, NKEY_D, NKEY_E, NKEY_F, NKEY_G,
    NKEY_H, NKEY_I, NKEY_J, NKEY_K, NKEY_L, NKEY_M, NKEY_N,
    NKEY_O, NKEY_P, NKEY_Q, NKEY_R, NKEY_S, NKEY_T, NKEY_U,
    NKEY_V, NKEY_W, NKEY_X, NKEY_Y, NKEY_Z,

    NKEY_0, NKEY_1, NKEY_2, NKEY_3, NKEY_4,
    NKEY_5, NKEY_6, NKEY_7, NKEY_8, NKEY_9,

    NKEY_ESCAPE,
    NKEY_TAB,
    NKEY_CAPS_LOCK,
    NKEY_BACKSPACE,
    NKEY_ENTER,
    NKEY_SPACE,

    NKEY_INSERT,
    NKEY_DELETE,
    NKEY_HOME,
    NKEY_END,
    NKEY_PAGE_UP,
    NKEY_PAGE_DOWN,

    NKEY_LEFT,
    NKEY_RIGHT,
    NKEY_UP,
    NKEY_DOWN,

    NKEY_F1, NKEY_F2, NKEY_F3, NKEY_F4, NKEY_F5, NKEY_F6,
    NKEY_F7, NKEY_F8, NKEY_F9, NKEY_F10, NKEY_F11, NKEY_F12,

    NKEY_LEFT_SHIFT,
    NKEY_RIGHT_SHIFT,
    NKEY_LEFT_CONTROL,
    NKEY_RIGHT_CONTROL,
    NKEY_LEFT_ALT,
    NKEY_RIGHT_ALT,
    NKEY_LEFT_SUPER,
    NKEY_RIGHT_SUPER,

    NKEY_PRINT_SCREEN,
    NKEY_SCROLL_LOCK,
    NKEY_PAUSE,

    NKEY_MINUS,
    NKEY_EQUALS,
    NKEY_LEFT_BRACKET,
    NKEY_RIGHT_BRACKET,
    NKEY_BACKSLASH,
    NKEY_SEMICOLON,
    NKEY_APOSTROPHE,
    NKEY_GRAVE,
    NKEY_COMMA,
    NKEY_PERIOD,
    NKEY_SLASH,

    NKEY_NUM_LOCK,
    NKEY_KP_DIVIDE,
    NKEY_KP_MULTIPLY,
    NKEY_KP_MINUS,
    NKEY_KP_PLUS,
    NKEY_KP_ENTER,
    NKEY_KP_0,
    NKEY_KP_1,
    NKEY_KP_2,
    NKEY_KP_3,
    NKEY_KP_4,
    NKEY_KP_5,
    NKEY_KP_6,
    NKEY_KP_7,
    NKEY_KP_8,
    NKEY_KP_9,
    NKEY_KP_PERIOD,

    NKEY_ANDROID_BACK,
    NKEY_ANDROID_MENU,
    NKEY_ANDROID_VOLUME_UP,
    NKEY_ANDROID_VOLUME_DOWN
};

enum class N_MOUSE_INPUT_EVENT : std::uint8_t {
    N_MOUSE_MOVED = 0,
    N_MOUSE_LEFT_DOWN,
    N_MOUSE_LEFT_UP,
    N_MOUSE_RIGHT_DOWN,
    N_MOUSE_RIGHT_UP,
    N_MOUSE_MIDDLE_DOWN,
    N_MOUSE_MIDDLE_UP,
    N_MOUSE_LEFT_DOUBLE_CLICK,
    N_MOUSE_RIGHT_DOUBLE_CLICK,
    N_MOUSE_MIDDLE_DOUBLE_CLICK,
    N_MOUSE_LEFT_TRIPLE_CLICK,
    N_MOUSE_RIGHT_TRIPLE_CLICK,
    N_MOUSE_MIDDLE_TRIPLE_CLICK,
    N_MOUSE_WHEEL,
    N_MOUSE_HWHEEL
};

enum class N_TOUCH_PHASE : std::uint8_t {
    N_TOUCH_DOWN = 0,
    N_TOUCH_UP,
    N_TOUCH_MOVE,
    N_TOUCH_CANCEL
};

} // namespace N
