#include <Nova3D/Assets/AssetPipeline.hpp>
#include <functional>

namespace nova3d::assets {
AssetGUID AssetGUID::fromPath(std::string_view path) { return {std::to_string(std::hash<std::string_view>{}(path))}; }
void AssetDatabase::registerAsset(AssetMetadata metadata){ if(metadata.guid.value.empty()) metadata.guid=AssetGUID::fromPath(metadata.sourcePath); auto it=m_guidToIndex.find(metadata.guid.value); if(it!=m_guidToIndex.end()){m_manifest.entries[it->second]=std::move(metadata);return;} const auto idx=m_manifest.entries.size(); m_pathToIndex[metadata.sourcePath]=idx; m_guidToIndex[metadata.guid.value]=idx; m_manifest.entries.push_back(std::move(metadata)); }
const AssetMetadata* AssetDatabase::findByGuid(const AssetGUID& guid) const { auto it=m_guidToIndex.find(guid.value); return it==m_guidToIndex.end()?nullptr:&m_manifest.entries[it->second]; }
const AssetMetadata* AssetDatabase::findByPath(std::string_view path) const { auto it=m_pathToIndex.find(std::string(path)); return it==m_pathToIndex.end()?nullptr:&m_manifest.entries[it->second]; }
std::vector<const AssetMetadata*> AssetDatabase::findByType(std::string_view typeName) const { std::vector<const AssetMetadata*> out; for (const auto& e: m_manifest.entries) if (e.typeName==typeName) out.push_back(&e); return out; }
std::vector<const AssetMetadata*> AssetResolver::resolveDependencies(const AssetGUID& guid) const { std::vector<const AssetMetadata*> out; if (const auto* m = m_db.findByGuid(guid)) for (const auto& dep:m->dependencies) if (const auto* d=m_db.findByGuid(dep)) out.push_back(d); return out; }
std::string serializeAssetMetadata(const AssetMetadata& metadata){ serialization::JsonValue::object_t root; root["guid"]=metadata.guid.value; root["sourcePath"]=metadata.sourcePath; root["typeName"]=metadata.typeName; serialization::JsonValue::array_t deps; for (const auto& d: metadata.dependencies) deps.push_back(d.value); root["dependencies"]=std::move(deps); serialization::JsonValue::object_t tags; for (const auto& [k,v]: metadata.tags) tags[k]=v; root["tags"]=std::move(tags); return serialization::JsonWriter::write(serialization::JsonValue(std::move(root))); }
std::optional<AssetMetadata> deserializeAssetMetadata(const std::string& json){ auto v=serialization::JsonParser::parse(json); if(!v || !v->isObject()) return std::nullopt; AssetMetadata out; const auto& o=v->asObject(); auto it=o.find("guid"); if(it!=o.end()&&it->second.isString()) out.guid.value=it->second.asString(); it=o.find("sourcePath"); if(it!=o.end()&&it->second.isString()) out.sourcePath=it->second.asString(); it=o.find("typeName"); if(it!=o.end()&&it->second.isString()) out.typeName=it->second.asString(); it=o.find("dependencies"); if(it!=o.end()&&it->second.isArray()) for(const auto& d:it->second.asArray()) if(d.isString()) out.dependencies.push_back({d.asString()}); it=o.find("tags"); if(it!=o.end()&&it->second.isObject()) for(const auto& [k,v]:it->second.asObject()) if(v.isString()) out.tags[k]=v.asString(); return out; }
}
