#include "OpenGLRenderBackend.hpp"
#include <Nova3D/Core/Logger.hpp>
#include <Nova3D/Platform/IWindow.hpp>
#include <SDL.h>
#if defined(__ANDROID__)
#include <GLES3/gl3.h>
#else
#define GLEW_NO_GLU
#include <GL/glew.h>
#include <SDL_opengl.h>
#endif
namespace nova3d::graphics {
static unsigned int compileStage(unsigned int t,const std::string& s){auto id=glCreateShader(t); const char* c=s.c_str(); glShaderSource(id,1,&c,nullptr); glCompileShader(id); return id;}
OpenGLShader::~OpenGLShader(){ if(m_program) glDeleteProgram(m_program);} 
bool OpenGLShader::compile(const std::string& vs,const std::string& fs){ auto v=compileStage(GL_VERTEX_SHADER,vs); auto f=compileStage(GL_FRAGMENT_SHADER,fs); m_program=glCreateProgram(); glAttachShader(m_program,v); glAttachShader(m_program,f); glLinkProgram(m_program); glDeleteShader(v); glDeleteShader(f); int linked=0; glGetProgramiv(m_program, GL_LINK_STATUS, &linked); return linked==GL_TRUE;}
int OpenGLShader::uniform(const std::string& n){ auto it=m_uniformCache.find(n); if(it!=m_uniformCache.end()) return it->second; int l=glGetUniformLocation(m_program,n.c_str()); m_uniformCache[n]=l; return l; }
void OpenGLShader::bind(){ glUseProgram(m_program);} void OpenGLShader::unbind(){ glUseProgram(0);} bool OpenGLShader::setUniformFloat(const std::string& n,float v){int l=uniform(n); if(l<0)return false; glUniform1f(l,v); return true;} bool OpenGLShader::setUniformVec3(const std::string& n,float x,float y,float z){int l=uniform(n); if(l<0)return false; glUniform3f(l,x,y,z); return true;} bool OpenGLShader::setUniformVec4(const std::string& n,float x,float y,float z,float w){int l=uniform(n); if(l<0)return false; glUniform4f(l,x,y,z,w); return true;} bool OpenGLShader::setUniformMat4(const std::string& n,const math::Matrix4& m){int l=uniform(n); if(l<0) return false; glUniformMatrix4fv(l,1,GL_FALSE,m.m.data()); return true;}
OpenGLTexture::~OpenGLTexture(){ if(m_id) glDeleteTextures(1,&m_id);} bool OpenGLTexture::upload(const ImageData& i){ if(!m_id) glGenTextures(1,&m_id); m_width=i.width;m_height=i.height; bind(0); GLenum fmt=i.format==TextureFormat::RGBA8?GL_RGBA:GL_RGB; glTexImage2D(GL_TEXTURE_2D,0,fmt,i.width,i.height,0,fmt,GL_UNSIGNED_BYTE,i.pixels.data()); glGenerateMipmap(GL_TEXTURE_2D); return true;} void OpenGLTexture::bind(std::uint32_t s){ glActiveTexture(GL_TEXTURE0+s); glBindTexture(GL_TEXTURE_2D,m_id);} void OpenGLTexture::unbind(){ glBindTexture(GL_TEXTURE_2D,0);} void OpenGLTexture::setFilter(TextureFilter min,TextureFilter mag){ glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,min==TextureFilter::Linear?GL_LINEAR_MIPMAP_LINEAR:GL_NEAREST); glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,mag==TextureFilter::Linear?GL_LINEAR:GL_NEAREST);} void OpenGLTexture::setWrap(TextureWrap u,TextureWrap v){ glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S,u==TextureWrap::Repeat?GL_REPEAT:GL_CLAMP_TO_EDGE); glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T,v==TextureWrap::Repeat?GL_REPEAT:GL_CLAMP_TO_EDGE);} 

OpenGLRenderTarget::OpenGLRenderTarget(int w,int h,bool depthOnly):m_width(w),m_height(h),m_depthOnly(depthOnly){ rebuild(); }
OpenGLRenderTarget::~OpenGLRenderTarget(){ if(m_fbo) glDeleteFramebuffers(1,&m_fbo); }
void OpenGLRenderTarget::resize(int w,int h){ m_width=w; m_height=h; rebuild(); }
bool OpenGLRenderTarget::bind(){ glBindFramebuffer(GL_FRAMEBUFFER,m_fbo); return true; }
void OpenGLRenderTarget::unbind(){ glBindFramebuffer(GL_FRAMEBUFFER,0); }
bool OpenGLRenderTarget::rebuild(){ if(!m_fbo) glGenFramebuffers(1,&m_fbo); glBindFramebuffer(GL_FRAMEBUFFER,m_fbo); if(!m_depthOnly){ if(!m_color) m_color=std::make_shared<OpenGLTexture>(); ImageData img{}; img.width=m_width; img.height=m_height; img.format=TextureFormat::RGBA8; img.pixels.resize((size_t)m_width*(size_t)m_height*4U); m_color->upload(img); glFramebufferTexture2D(GL_FRAMEBUFFER,GL_COLOR_ATTACHMENT0,GL_TEXTURE_2D,m_color->id(),0);} if(!m_depth) m_depth=std::make_shared<OpenGLDepthTexture>(); if(!m_depth->m_id) glGenTextures(1,&m_depth->m_id); m_depth->m_width=m_width; m_depth->m_height=m_height; glBindTexture(GL_TEXTURE_2D,m_depth->m_id); glTexImage2D(GL_TEXTURE_2D,0,GL_DEPTH_COMPONENT24,m_width,m_height,0,GL_DEPTH_COMPONENT,GL_UNSIGNED_INT,nullptr); glFramebufferTexture2D(GL_FRAMEBUFFER,GL_DEPTH_ATTACHMENT,GL_TEXTURE_2D,m_depth->m_id,0); if(m_depthOnly){ glDrawBuffer(GL_NONE); glReadBuffer(GL_NONE);} bool ok=glCheckFramebufferStatus(GL_FRAMEBUFFER)==GL_FRAMEBUFFER_COMPLETE; glBindFramebuffer(GL_FRAMEBUFFER,0); return ok; }
OpenGLVertexBuffer::~OpenGLVertexBuffer(){ if(m_id) glDeleteBuffers(1,&m_id); if(m_vao) glDeleteVertexArrays(1,&m_vao);} bool OpenGLVertexBuffer::upload(const void* d,std::size_t b,const VertexLayout& layout){ if(!m_id) glGenBuffers(1,&m_id); if(!m_vao) glGenVertexArrays(1,&m_vao); glBindVertexArray(m_vao); glBindBuffer(GL_ARRAY_BUFFER,m_id); glBufferData(GL_ARRAY_BUFFER,(GLsizeiptr)b,d,GL_STATIC_DRAW); for(std::size_t i=0;i<layout.attributeCount;++i){ const auto&a=layout.attributes[i]; glEnableVertexAttribArray(a.location); glVertexAttribPointer(a.location,(GLint)a.components,GL_FLOAT,GL_FALSE,(GLsizei)layout.stride,(void*)a.offset);} return true;} void OpenGLVertexBuffer::bind(){ glBindVertexArray(m_vao); glBindBuffer(GL_ARRAY_BUFFER,m_id);} void OpenGLVertexBuffer::unbind(){ glBindVertexArray(0); glBindBuffer(GL_ARRAY_BUFFER,0);} 
OpenGLIndexBuffer::~OpenGLIndexBuffer(){ if(m_id) glDeleteBuffers(1,&m_id);} bool OpenGLIndexBuffer::upload(const std::uint32_t* d,std::size_t c){ if(!m_id) glGenBuffers(1,&m_id); m_count=c; glBindBuffer(GL_ELEMENT_ARRAY_BUFFER,m_id); glBufferData(GL_ELEMENT_ARRAY_BUFFER,(GLsizeiptr)(sizeof(std::uint32_t)*c),d,GL_STATIC_DRAW); return true;} void OpenGLIndexBuffer::bind(){ glBindBuffer(GL_ELEMENT_ARRAY_BUFFER,m_id);} void OpenGLIndexBuffer::unbind(){ glBindBuffer(GL_ELEMENT_ARRAY_BUFFER,0);} 
void BasicMaterial::bind(){ if(m_shader) m_shader->bind(); for(auto& [slot,tex]:m_textures) if(tex) tex->bind(slot);} void BasicMaterial::unbind(){ for(auto& [slot,tex]:m_textures) if(tex) tex->unbind(); if(m_shader) m_shader->unbind(); }
void OpenGLVideoDriver::beginFrame(){} void OpenGLVideoDriver::endFrame(){} void OpenGLVideoDriver::setRenderTarget(const std::shared_ptr<IRenderTarget>& target){ if(!target){ OpenGLRenderTarget::unbind(); return;} auto rt=std::dynamic_pointer_cast<OpenGLRenderTarget>(target); if(rt) rt->bind(); } void OpenGLVideoDriver::clear(const Color& c,bool d){ glClearColor(c.r,c.g,c.b,c.a); glClear(d?(GL_COLOR_BUFFER_BIT|GL_DEPTH_BUFFER_BIT):GL_COLOR_BUFFER_BIT);} void OpenGLVideoDriver::setViewport(const Viewport& v){ glViewport(v.x,v.y,v.width,v.height);} void OpenGLVideoDriver::setRenderState(const RenderState& s){ if(!m_hasCachedState||s.depthTest!=m_cachedState.depthTest) s.depthTest?glEnable(GL_DEPTH_TEST):glDisable(GL_DEPTH_TEST); if(!m_hasCachedState||s.depthWrite!=m_cachedState.depthWrite) glDepthMask(s.depthWrite?GL_TRUE:GL_FALSE); if(!m_hasCachedState||s.culling!=m_cachedState.culling) s.culling?glEnable(GL_CULL_FACE):glDisable(GL_CULL_FACE); if(!m_hasCachedState||s.wireframe!=m_cachedState.wireframe) glPolygonMode(GL_FRONT_AND_BACK,s.wireframe?GL_LINE:GL_FILL); if(!m_hasCachedState||s.blending!=m_cachedState.blending) s.blending?glEnable(GL_BLEND):glDisable(GL_BLEND); m_cachedState=s; m_hasCachedState=true;} void OpenGLVideoDriver::drawIndexed(PrimitiveType,std::size_t c){ glDrawElements(GL_TRIANGLES,(GLsizei)c,GL_UNSIGNED_INT,nullptr);} std::shared_ptr<IShader> OpenGLVideoDriver::createShader(){ return std::make_shared<OpenGLShader>(); } std::shared_ptr<ITexture> OpenGLVideoDriver::createTexture(){ return std::make_shared<OpenGLTexture>(); } std::shared_ptr<IRenderTarget> OpenGLVideoDriver::createRenderTarget(int width,int height,bool depthOnly){ return std::make_shared<OpenGLRenderTarget>(width,height,depthOnly);} std::shared_ptr<IVertexBuffer> OpenGLVideoDriver::createVertexBuffer(){ return std::make_shared<OpenGLVertexBuffer>(); } std::shared_ptr<IIndexBuffer> OpenGLVideoDriver::createIndexBuffer(){ return std::make_shared<OpenGLIndexBuffer>(); } std::shared_ptr<IMaterial> OpenGLVideoDriver::createMaterial(){ return std::make_shared<BasicMaterial>(); }
bool OpenGLRenderContextDesktop::initialize(platform::IWindow& window) { m_window=&window; SDL_GL_SetAttribute(SDL_GL_DOUBLEBUFFER,1); SDL_GL_SetAttribute(SDL_GL_DEPTH_SIZE,24); m_context=SDL_GL_CreateContext(window.sdlWindow()); if(!m_context){ core::Logger::error("SDL_GL_CreateContext failed"); return false;} SDL_GL_SetSwapInterval(1); int w=0,h=0; window.getSize(w,h); resize(w,h); return true; }
void OpenGLRenderContextDesktop::shutdown(){ if(m_context){ SDL_GL_DeleteContext(m_context); m_context=nullptr; }} void OpenGLRenderContextDesktop::beginFrame(){ m_videoDriver.beginFrame(); m_videoDriver.clear({0.1F,0.15F,0.2F,1.0F}, true);} void OpenGLRenderContextDesktop::endFrame(){ m_videoDriver.endFrame(); if(m_window) m_window->swapBuffers(); } void OpenGLRenderContextDesktop::resize(int width, int height){ m_videoDriver.setViewport({0,0,width,height}); }
}
