#pragma once
#include <memory>
#include <unordered_map>
#include <Nova3D/Graphics/IRenderContext.hpp>
#include <Nova3D/Graphics/IRenderer.hpp>
using SDL_GLContext = void*;
namespace nova3d::graphics {
class OpenGLShader final : public IShader { public: ~OpenGLShader() override; bool compile(const std::string&, const std::string&) override; void bind() override; void unbind() override; bool setUniformFloat(const std::string&, float) override; bool setUniformVec3(const std::string&, float,float,float) override; bool setUniformVec4(const std::string&, float,float,float,float) override; bool setUniformMat4(const std::string&, const math::Matrix4&) override; private: int uniform(const std::string&); unsigned int m_program=0; std::unordered_map<std::string,int> m_uniformCache;};
class OpenGLTexture : public ITexture { public: ~OpenGLTexture() override; bool upload(const ImageData&) override; void bind(std::uint32_t) override; void unbind() override; void setFilter(TextureFilter, TextureFilter) override; void setWrap(TextureWrap, TextureWrap) override; int width() const override { return m_width; } int height() const override { return m_height; } unsigned int id() const { return m_id; } public: unsigned int m_id=0; int m_width=0,m_height=0;};
class OpenGLDepthTexture final : public OpenGLTexture {};
class OpenGLRenderTarget final : public IRenderTarget { public: OpenGLRenderTarget(int w,int h,bool depthOnly); ~OpenGLRenderTarget() override; int width() const override { return m_width;} int height() const override { return m_height;} void resize(int w,int h) override; bool bind(); static void unbind(); private: bool rebuild(); int m_width; int m_height; bool m_depthOnly; unsigned int m_fbo=0; std::shared_ptr<OpenGLTexture> m_color; std::shared_ptr<OpenGLDepthTexture> m_depth; friend class OpenGLVideoDriver;};
class OpenGLVertexBuffer final : public IVertexBuffer { public: ~OpenGLVertexBuffer() override; bool upload(const void*,std::size_t,const VertexLayout&) override; void bind() override; void unbind() override; private: unsigned int m_id=0,m_vao=0;};
class OpenGLIndexBuffer final : public IIndexBuffer { public: ~OpenGLIndexBuffer() override; bool upload(const std::uint32_t*,std::size_t) override; std::size_t indexCount() const override { return m_count; } void bind() override; void unbind() override; private: unsigned int m_id=0; std::size_t m_count=0;};
class BasicMaterial final : public IMaterial { public: void setShader(const std::shared_ptr<IShader>& s) override { m_shader=s; } void setTexture(std::uint32_t slot,const std::shared_ptr<ITexture>& t) override { m_textures[slot]=t; } void setState(const RenderState& s) override { m_state=s; } const RenderState& state() const override { return m_state; } bool isTransparent() const override { return m_state.blending; } void bind() override; void unbind() override; private: std::shared_ptr<IShader> m_shader; std::unordered_map<std::uint32_t,std::shared_ptr<ITexture>> m_textures; RenderState m_state{};};
class OpenGLVideoDriver final : public IVideoDriver { public: void beginFrame() override; void endFrame() override; void clear(const Color&, bool) override; void setViewport(const Viewport&) override; void setRenderState(const RenderState&) override; void setRenderTarget(const std::shared_ptr<IRenderTarget>& target) override; void drawIndexed(PrimitiveType,std::size_t) override; std::shared_ptr<IShader> createShader() override; std::shared_ptr<ITexture> createTexture() override; std::shared_ptr<IRenderTarget> createRenderTarget(int width,int height,bool depthOnly) override; std::shared_ptr<IVertexBuffer> createVertexBuffer() override; std::shared_ptr<IIndexBuffer> createIndexBuffer() override; std::shared_ptr<IMaterial> createMaterial() override; private: RenderState m_cachedState{}; bool m_hasCachedState=false;};
class OpenGLRenderContextDesktop : public IRenderContext { public: bool initialize(platform::IWindow&) override; void shutdown() override; void beginFrame() override; void endFrame() override; void resize(int,int) override; IVideoDriver& videoDriver() override { return m_videoDriver; } private: platform::IWindow* m_window=nullptr; SDL_GLContext m_context=nullptr; OpenGLVideoDriver m_videoDriver;};
class OpenGLESRenderContextAndroid final : public OpenGLRenderContextDesktop {};
}
