#include <Nova3D/Graphics/RenderPipeline/ForwardRenderer.hpp>
namespace nova3d::graphics {
namespace {
class BeginFramePass final: public RenderPass { void execute(IVideoDriver& d, scene::SceneManager& s, const CameraRenderContext& c) override { d.setRenderTarget(c.target); d.setViewport(c.viewport); d.beginFrame(); d.clear({0.08F,0.1F,0.13F,1.0F}, true); s.gather(); } };
class ShadowPreparationPass final: public RenderPass { void execute(IVideoDriver&, scene::SceneManager&, const CameraRenderContext&) override {} };
class OpaquePass final: public RenderPass { void execute(IVideoDriver& d, scene::SceneManager& s, const CameraRenderContext& c) override { for(auto& item:s.opaqueQueue()){ auto vb=d.createVertexBuffer(); auto ib=d.createIndexBuffer(); VertexLayout l{}; l.stride=sizeof(scene::Vertex); l.attributeCount=4; l.attributes[0]={VertexSemantic::Position,0,3,offsetof(scene::Vertex,position)}; l.attributes[1]={VertexSemantic::Normal,1,3,offsetof(scene::Vertex,normal)}; l.attributes[2]={VertexSemantic::UV0,2,2,offsetof(scene::Vertex,uv)}; l.attributes[3]={VertexSemantic::Color0,3,4,offsetof(scene::Vertex,color)}; vb->upload(item.meshBuffer->vertices().data(),item.meshBuffer->vertices().size()*sizeof(scene::Vertex),l); ib->upload(item.meshBuffer->indices().data(),item.meshBuffer->indices().size()); if(auto m=item.meshBuffer->material()){ d.setRenderState(m->state()); m->bind(); }
 vb->bind(); ib->bind(); d.drawIndexed(item.meshBuffer->primitiveType(), ib->indexCount()); if(auto m=item.meshBuffer->material()) m->unbind(); }} };
class TransparentPass final: public RenderPass { void execute(IVideoDriver& d, scene::SceneManager& s, const CameraRenderContext&) override { for(auto& item:s.transparentQueue()){ auto vb=d.createVertexBuffer(); auto ib=d.createIndexBuffer(); VertexLayout l{}; l.stride=sizeof(scene::Vertex); l.attributeCount=4; l.attributes[0]={VertexSemantic::Position,0,3,offsetof(scene::Vertex,position)}; l.attributes[1]={VertexSemantic::Normal,1,3,offsetof(scene::Vertex,normal)}; l.attributes[2]={VertexSemantic::UV0,2,2,offsetof(scene::Vertex,uv)}; l.attributes[3]={VertexSemantic::Color0,3,4,offsetof(scene::Vertex,color)}; vb->upload(item.meshBuffer->vertices().data(),item.meshBuffer->vertices().size()*sizeof(scene::Vertex),l); ib->upload(item.meshBuffer->indices().data(),item.meshBuffer->indices().size()); if(auto m=item.meshBuffer->material()){ d.setRenderState(m->state()); m->bind(); } vb->bind(); ib->bind(); d.drawIndexed(item.meshBuffer->primitiveType(), ib->indexCount()); if(auto m=item.meshBuffer->material()) m->unbind(); }} };
class EndFramePass final: public RenderPass { void execute(IVideoDriver& d, scene::SceneManager&, const CameraRenderContext&) override { d.endFrame(); } };
}
ForwardRenderer::ForwardRenderer(IVideoDriver& driver):m_driver(driver){ m_passes.push_back(std::make_unique<BeginFramePass>()); m_passes.push_back(std::make_unique<ShadowPreparationPass>()); m_passes.push_back(std::make_unique<OpaquePass>()); m_passes.push_back(std::make_unique<TransparentPass>()); m_passes.push_back(std::make_unique<EndFramePass>());} 
void ForwardRenderer::render(scene::SceneManager& scene){ auto cam=scene.activeCamera(); if(!cam) return; CameraRenderContext ctx{cam->viewMatrix(),cam->projectionMatrix(),cam->viewProjectionMatrix(),cam->viewport(),cam->renderTarget()}; for(auto& p:m_passes) p->execute(m_driver,scene,ctx);} 
}
